# Generated by Django 2.2.12 on 2020-12-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=42)),
                ('company', models.TextField()),
                ('item_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=42)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('MRP', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('mfg_date', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('cus_name', models.CharField(max_length=42)),
                ('sell_price', models.FloatField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop')),
            ],
        ),
    ]
