# Generated by Django 2.2.12 on 2021-01-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock'),
        ),
        migrations.DeleteModel(
            name='wares',
        ),
    ]
